# run command: docker-compose -f docker-compose_volume.yml up
version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql # host의 {volumePath}/db-data <-> container의 /var/lib/mysql 매핑


volumes:
  db-data: # host의 volume명 (directory명)
    driver: local